(()=>{'use strict';
const root=document.querySelector('#app');
const s={screen:'home',scenario:'normal',timer:null,progress:0,soc:0,power:0,efficiency:94,elapsed:0,taps:0,admin:false};
const relay=phase=>window.wipKiosk?.relay?.setState({product:'EV',phase}).catch(()=>{});
const relayPhaseFor=screen=>({home:'idle',detect:'detected',align:'aligning',ready:'ready',charge:'charging',fault:'fault',complete:'complete'})[screen]||'idle';
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const step=n=>`<div class="steps four">${[['01','차량 진입'],['02','FOD 검사'],['03','PD 위치 확인'],['04','충전 진행']].map((x,i)=>`${i?'<i></i>':''}<span class="${n>i?'on':''}"><b>${x[0]}</b>${x[1]}</span>`).join('')}</div>`;
const header=n=>`<header><button class="logo" data-action="admin"><b>WIP</b><span>WIRELESS POWER<br><small>CHARGING SYSTEM</small></span></button><div class="top-state"><i></i>SYSTEM ONLINE${n?`<em>${n} / 4</em>`:''}</div></header>`;
const formatBody=body=>{let v=body.replaceAll('충전 영역에서 사람 또는 동물로 판단되는 생체 신호를 감지했습니다.','차량과 충전 패드의 중심 위치가 허용 범위를 벗어났습니다.').replaceAll('사람·동물 생체 신호 감지','차량·패드 위치 불일치').replaceAll('생체가 감지되었습니다','위치 오차가 감지되었습니다').replaceAll('BIOLOGICAL OBJECT','POSITION MISALIGNMENT').replaceAll('PERSON / ANIMAL','OUT OF POSITION').replaceAll('POSITION · PRESENCE DETECTION','POSITION DETECTION').replaceAll('PD BIOLOGICAL DETECTION','PD POSITION DETECTION').replaceAll('로보택시','차량').replaceAll('자율주행 차량','차량').replaceAll('금속·생체 이물질','금속성 이물질').replaceAll('PD 생체 감지','PD 위치 감지').replaceAll('PD 생체','PD 위치').replaceAll('위치·생체','차량·패드 위치').replaceAll('차량 충전 중','무선 전력 공급 중').replaceAll('차량 충전이<br>완료되었습니다.','무선전력 공급이<br>완료되었습니다.');if(s.screen==='align')v=v.replace('SMART POSITIONING','FOD PAD SCAN').replace('충전 패드를<br>정렬하고 있습니다.','무선충전 패드를<br>검사하고 있습니다.').replace('영상처럼 차량 수신 코일과 지면 급전 코일의 중심을 맞춥니다.','차량 앞쪽 하부의 무선충전 패드 전면을 스캔합니다.');if(s.screen==='ready')v=v.replace('READY TO CHARGE','TOP VIEW POSITION CHECK').replace('안전 확인이<br>완료되었습니다.','차량과 패드의<br>위치를 확인합니다.').replace('<button class="primary wide" data-action="charge">충전 시작 ⚡</button>','<button class="primary wide analyzing-button" data-action="charge" disabled>PD 위치 분석 중…</button>');return v};
const shell=(body,n=0)=>`<div class="app">${header(n)}${formatBody(body).replaceAll('금속 및 생체 이물질 감지 영역 활성화','금속성 이물질 검출 및 위치 확인 활성화').replaceAll('무선 전력 공급 중','Wireless 충전 중 . . .')}<footer><span>AI 기반 위치 인식</span><span>금속성 이물질 검출(FOD)</span><span>무선전력 충전 시스템</span></footer></div>${s.admin?admin():''}`;
const taxi=(mode='idle')=>mode==='idle'?`<div class="taxi idle"><img src="assets/kia-pbv-hero-v2.png" alt="기아 PBV"><span class="lidar">AI POSITIONING <b>READY</b></span></div>`:bay(({scan:'entering',aligning:'fod',ready:'pd',charging:'charging',hazard:`${s.scenario} hazard-bay`,completed:'completed'})[mode]||mode);
const bay=mode=>`<div class="bay-scene ${mode}"><img class="bay-bg" src="assets/charging-bay-top.png" alt="무선충전 패드"><div class="legacy-pad-mask"></div><img class="active-pad" src="assets/pha-wip-ground-pad.png" alt="PHA-WIP 급전패드"><span class="pad-rating">GA · 50 kW</span><img class="moving-car${mode==="charging"?" front-view":""}" src="${mode==="charging"?"assets/kia-pbv-front-charge.png":"assets/kia-pbv-top.png"}" alt="진입하는 기아 PBV">${mode==='fod'?'<div class="bay-mode fod-mode"><i></i><span><small>FOREIGN OBJECT DETECTION</small><b>FOD 무선충전 패드 검사 중</b></span><em>SCANNING</em></div>':mode==='pd'?'<div class="bay-mode pd-mode"><i></i><span><small>POSITION DETECTION</small><b>PD 차량·패드 위치 확인 중</b></span><em>ANALYZING</em></div>':''}<div class="bay-pad-scan"><i></i></div><div class="bay-target"><i></i><i></i><span>PAD CENTER</span></div>${mode==='charging'?'<div class="power-badge"><small>HIGH POWER WIRELESS CHARGING</small><b>50 kW</b></div><div class="magnetic-field"><i></i><i></i><i></i><i></i></div><div class="receiver-coil"><i></i><i></i><b>VA · RX COIL</b></div><div class="underbody-battery"><span><i></i></span><b>BATTERY</b></div><div class="energy-route"><i></i><i></i><i></i><i></i><i></i></div><div class="bay-energy"><i></i><i></i><i></i><b class="live-power">0.0 kW</b></div>':''}</div>`;
const caption=(a,b)=>`<div class="visual-caption"><b>${a}</b><span>${b}</span></div>`;
const rows=items=>`<div class="ready-list">${items.map(x=>`<span><i>${x[2]?'✓':'·'}</i><b>${x[0]}</b><em>${x[1]}</em></span>`).join('')}</div>`;
function home(){return shell(`<main class="hero pbv-hero"><div class="pbv-backdrop"></div><div class="copy"><span class="eyebrow">KIA PBV · WIRELESS POWER</span><h1>멈추는 순간,<br><em>무선전력 충전이 시작됩니다.</em></h1><p>기아 PBV 시연을 위한 PHA-WIP 무선충전 시스템<br>11~150 kW 기술 범위 · 최대 94% 시스템 효율</p><button class="primary" data-action="begin">자동 시연 시작 <b>→</b></button><div class="mini"><span>⚡ <b>50 kW</b> 급속 무선충전</span><span>◈ <b>최대 94%</b> 시스템 효율</span><span>◇ <b>FOD · LOP · PD</b> 안전 감지</span></div></div></main>`)}
function detect(){return shell(`<main class="stage">${step(1)}<div class="stage-grid"><section>${taxi('scan')}<div class="sensor-sweep"></div>${caption('AI VEHICLE DETECTION','차량이 무선충전 구역으로 진입합니다')}</section><aside><span class="eyebrow">VEHICLE DETECTION</span><h2>차량을<br>인식하고 있습니다.</h2><p>차량 센서와 지면 패드의 위치 정보를 연결합니다.</p>${rows([['차량 감지',s.progress>20?'DETECTED':'SCANNING',s.progress>20],['AI 위치 통신',s.progress>55?'CONNECTED':'CONNECTING',s.progress>55],['충전 패드 확인',s.progress>85?'PAD FOUND':'SEARCHING',s.progress>85]])}<div class="progress"><i style="width:${s.progress}%"></i></div></aside></div></main>`,1)}
function align(){let p=Math.round(s.progress);return shell(`<main class="stage">${step(2)}<div class="stage-grid"><section>${taxi('aligning')}<div class="pad-outline"><i></i><i></i><b>${p}%</b></div>${caption('SMART PAD ALIGNMENT','GA 급전패드와 VA 집전장치의 중심을 정렬합니다')}</section><aside><span class="eyebrow">SMART POSITIONING · PD</span><h2>충전 패드를<br>정렬하고 있습니다.</h2><p>차량 전방 하부의 집전장치가 급전패드 중심에 위치하는지 확인합니다.</p><div class="align-data">${[['좌우 정렬',p+'%',p],['전후 정렬',Math.max(0,p-3)+'%',Math.max(0,p-3)],['패드 간격',Math.round(190-p*.6)+' mm',p]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b><i><em style="width:${x[2]}%"></em></i></div>`).join('')}</div></aside></div></main>`,2)}
function ready(){return shell(`<main class="stage">${step(3)}<div class="stage-grid"><section>${taxi('ready')}<div class="safety-field"><i>FOD</i><i>PD</i><span>360° SAFETY ZONE</span></div>${caption('FOD · PD SAFETY CHECK','금속 및 생체 이물질 감지 영역 활성화')}</section><aside><span class="eyebrow">READY TO CHARGE</span><h2>안전 확인이<br>완료되었습니다.</h2><p>안전 감지는 충전 중에도 계속 작동합니다.</p>${rows([['차량 위치','OPTIMAL',true],['FOD 금속 감지','CLEAR',true],['PD 생체 감지','CLEAR',true]])}<button class="primary wide" data-action="charge">충전 시작 ⚡</button></aside></div></main>`,3)}
const metric=(a,b,u,m='')=>`<div class="metric ${m}" ${m==='main'?`style="--value:${Number(b)||0}%"`:''}><span>${a}</span><strong>${b}<small>${u}</small></strong>${m==='main'?'<div class="soc-gauge"><i></i><em></em></div>':''}</div>`;
function charge(){return shell(`<main class="stage charging">${step(4)}<div class="charge-grid"><section>${taxi('charging')}${caption('PHA-WIP WIRELESS POWER TRANSFER','급전패드에서 차량 집전장치로 전력을 전송합니다')}<div class="charge-label"><i></i><span>50 kW POWER TRANSFER</span><b>ACTIVE</b></div></section><aside><div class="charge-title"><div><span class="eyebrow">KIA PBV CHARGING</span><h2>Wireless 충전 중 . . .</h2></div><span class="live"><i></i>LIVE</span></div><div class="metrics">${metric('SOC',Math.round(s.soc),'%','main')}${metric('전력',s.power.toFixed(1),' kW')}${metric('충전 효율',s.efficiency.toFixed(1),' %')}${metric('시간',fmt(s.elapsed),'')}</div><div class="safety"><div><span>AI SAFETY MONITOR</span><b>실시간 감지 중</b></div><span class="safe-chip"><i>✓</i>FOD 이물질<b>CLEAR</b></span><span class="safe-chip"><i>✓</i>LOP 생명체 보호<b>CLEAR</b></span><span class="safe-chip"><i>✓</i>PD 위치 감지<b>ALIGNED</b></span></div><button class="stop" data-action="stop">충전 정지</button></aside></div></main>`,4)}
function fault(){let pd=s.scenario==='pd';return shell(`<main class="hazard ${pd?'pd':'fod'}">${step(4)}<div class="hazard-grid"><section>${taxi('hazard')}<div class="detect-zone"><i class="object">${pd?'●':'◆'}</i><i class="ring r1"></i><i class="ring r2"></i><span>${pd?'BIOLOGICAL OBJECT':'METAL OBJECT'}</span></div>${caption(pd?'PD BIOLOGICAL DETECTION':'FOD METAL DETECTION',pd?'사람·동물 생체 신호 감지':'금속 이물질 감지')}</section><aside><span class="alarm">SAFETY PROTOCOL ACTIVE</span><div class="hazard-icon">${pd?'PD':'FOD'}</div><h2>${pd?'생체가 감지되었습니다':'금속 이물질이 감지되었습니다'}</h2><p>${pd?'충전 영역에서 사람 또는 동물로 판단되는 생체 신호를 감지했습니다.':'충전 패드 주변에서 금속성 이물질을 감지했습니다.'}<br>전력 출력을 즉시 차단했습니다.</p><dl><div><dt>감지 유형</dt><dd>${pd?'PERSON / ANIMAL':'METALLIC OBJECT'}</dd></div><div><dt>전력 출력</dt><dd>0.0 kW · DISABLED</dd></div></dl><div class="buttons"><button class="primary" data-action="retry">안전 확인 후 재시도</button><button data-action="home">홈으로</button></div></aside></div></main>`,4)}
function complete(){return shell(`<main class="complete-screen"><div class="victory-overlay"><div class="victory-burst"><i></i><i></i><i></i></div><span>SESSION CLEAR</span><strong>충전 완료</strong><b>80<small>%</small></b><em>50 kW 고출력 무선전력 공급이 완료되었습니다</em></div><div class="complete-scene">${taxi('completed')}<div class="complete-rings"><i></i><i></i><i></i><b>✓</b></div></div><aside><span class="eyebrow">CHARGING SESSION COMPLETE</span><h2>무선전력 공급이<br>완료되었습니다.</h2><p>무선충전 패드를 통한 50 kW 전력 공급이<br>안전하게 종료되었습니다.</p><div class="complete-data">${metric('최종 SOC','80','%')}${metric('정격 전력','50',' kW')}${metric('안전 감지','CLEAR','')}</div><button class="primary wide" data-action="home">처음 화면으로</button></aside></main>`,4)}
function admin(){return `<div class="overlay"><div class="admin"><button class="close" data-action="close">×</button><span>OPERATOR CONSOLE</span><h2>안전 시나리오</h2><p>충전 중 시연할 상태를 선택하세요.</p><div class="choices">${[['normal','정상 충전','FOD / PD CLEAR'],['fod','FOD 감지','금속 이물질'],['pd','PD 감지','사람 · 동물']].map(x=>`<button class="${s.scenario===x[0]?'selected':''}" data-scenario="${x[0]}"><i></i><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><button class="primary wide" data-action="run">선택 시나리오 실행</button></div></div>`}
function render(){let f={home,detect,align,ready,charge,fault,complete}[s.screen]||home;root.innerHTML=f();if(s.screen==='ready'&&!s.pdTimer){s.pdTimer=setTimeout(()=>{s.pdTimer=null;if(s.screen==='ready'){finishPd()}},4800)}}
function clear(){clearInterval(s.timer);s.timer=null}
function restartLoop(){clear();s.screen='home';s.scenario='normal';relay('idle');render();s.timer=setTimeout(()=>{if(s.screen==='home')animate('detect','align')},3000)}
function finishPd(){let btn=root.querySelector('[data-action="charge"]'),badge=root.querySelector('.pd-mode');if(btn){btn.disabled=false;btn.classList.remove('analyzing-button');btn.classList.add('ready-button');btn.innerHTML='무선 전력 공급 준비 ✓'}if(badge){badge.classList.add('complete-check');let title=badge.querySelector('b'),status=badge.querySelector('em');if(title)title.textContent='PD 차량·패드 위치 확인 완료';if(status)status.textContent='ALIGNED'}s.autoChargeTimer=setTimeout(()=>{s.autoChargeTimer=null;if(s.screen==='ready'&&s.scenario==='normal')startCharge()},900)}
function animate(screen,next,ms=3400){if(s.screen==='complete'&&screen==='detect'){restartLoop();return}clear();s.screen=screen;s.progress=100;relay(relayPhaseFor(screen));render();s.timer=setTimeout(()=>{s.timer=null;s.screen=next;relay(relayPhaseFor(next));render();if(next==='ready'&&s.scenario!=='normal')setTimeout(()=>{s.screen='fault';relay('fault');render()},1800)},ms)}
function startCharge(){clear();Object.assign(s,{screen:'charge',soc:0,power:0,efficiency:0,elapsed:0});relay('charging');render();const started=performance.now(),duration=60000,ramp=5000;const update=()=>{const ms=performance.now()-started,ratio=Math.min(1,ms/duration),chargeRatio=Math.max(0,Math.min(1,(ms-ramp)/(duration-ramp)));s.elapsed=ms/1000;s.power=ms<ramp?50*(ms/ramp):50;s.soc=80*chargeRatio;s.efficiency=Math.min(100,(s.power/50)*100);const values=root.querySelectorAll('.metrics .metric strong');if(values[0])values[0].innerHTML=`${Math.round(s.soc)}<small>%</small>`;if(values[1])values[1].innerHTML=`${s.power.toFixed(1)}<small> kW</small>`;if(values[2])values[2].innerHTML=`${s.efficiency.toFixed(1)}<small> %</small>`;if(values[3])values[3].textContent=fmt(s.elapsed);const main=root.querySelector('.metric.main'),gauge=root.querySelector('.soc-gauge i'),battery=root.querySelector('.underbody-battery span i'),livePower=root.querySelector('.live-power'),title=root.querySelector('.charge-title h2'),label=root.querySelector('.charge-label b');const gaugePercent=s.soc/80*100;if(main)main.style.setProperty('--value',`${gaugePercent}%`);if(gauge)gauge.style.width=`${gaugePercent}%`;if(battery)battery.style.height=`${gaugePercent}%`;if(livePower)livePower.textContent=`${s.power.toFixed(1)} kW`;if(title)title.textContent=ms<ramp?'50 kW 전력 준비 중 . . .':'Wireless 충전 중 . . .';if(label)label.textContent=ms<ramp?'POWER RAMP-UP':'50 kW ACTIVE';if(s.scenario!=='normal'&&ms>=2000){clear();s.screen='fault';relay('fault');render();setTimeout(()=>{s.scenario='normal';restartLoop()},4000);return}if(ratio>=1){clear();s.soc=80;s.power=50;s.screen='complete';relay('complete');render();setTimeout(()=>{if(s.screen==='complete')restartLoop()},6200)}};s.timer=setInterval(update,50);update()}
root.addEventListener('click',e=>{let el=e.target.closest('[data-action],[data-scenario]');if(!el)return;if(el.dataset.scenario){s.scenario=el.dataset.scenario;render();return}let a=el.dataset.action;if(a==='admin'){if(++s.taps>=5){s.taps=0;s.admin=true;render()}return}if(a==='begin')animate('detect','align');if(a==='charge')startCharge();if(a==='stop'){s.scenario='fod';s.screen='fault';clear();relay('fault')}if(a==='retry'){s.scenario='normal';s.screen='ready';relay('ready')}if(a==='home'){clear();s.screen='home';relay('idle')}if(a==='close')s.admin=false;if(a==='run'){s.admin=false;animate('detect','align')}render()});
const watch=setInterval(()=>{if(s.screen==='align'&&!s.timer)animate('align','ready')},300);render();s.timer=setTimeout(()=>{if(s.screen==='home')animate('detect','align')},3000);
})();

