(()=>{'use strict';
const root=document.querySelector('#app');
const chargeConfig=Object.freeze({batteryCapacityKWh:71.2,startSocPercent:20,targetSocPercent:80,nominalPowerKw:50,demoDurationMs:60000,powerReadyMs:5000});
const demoTiming=Object.freeze({homeMs:8000,pairingMs:6000,fodMs:6500,lodLopMs:7500,stageCompleteMs:1500,pdMs:7000,pdCompleteMs:2200,completeMs:10000});
const stageDuration=Object.freeze({detect:demoTiming.pairingMs,align:demoTiming.fodMs,living:demoTiming.lodLopMs});
const stageChecks=Object.freeze({
  detect:[['차량 감지','VEHICLE DETECTED','SCANNING',25],['통신 연결','LINK CONNECTED','CONNECTING',55],['세션 페어링','PAIRING VERIFIED','VERIFYING',85]],
  align:[['급전패드 영역','PAD SCANNED','SCANNING',25],['금속성 이물질','NO OBJECT','CHECKING',60],['FOD 상태','CLEAR','VERIFYING',90]],
  living:[['생체 접근 영역','AREA SCANNED','SCANNING',25],['살아 있는 대상','NOT DETECTED','CHECKING',60],['LOP 보호 시스템','ARMED','ACTIVATING',90]]
});
const targetEnergyKWh=chargeConfig.batteryCapacityKWh*(chargeConfig.targetSocPercent-chargeConfig.startSocPercent)/100;
const targetElapsedSeconds=targetEnergyKWh/chargeConfig.nominalPowerKw*3600;
const chargeSample=progress=>{const ratio=Math.max(0,Math.min(1,progress)),energy=targetEnergyKWh*ratio;return{soc:Math.min(chargeConfig.targetSocPercent,chargeConfig.startSocPercent+energy/chargeConfig.batteryCapacityKWh*100),energy,elapsed:targetElapsedSeconds*ratio}};
const s={screen:'home',scenario:'normal',timer:null,progress:0,soc:chargeConfig.startSocPercent,power:0,energy:0,elapsed:0,taps:0,admin:false};
const relay=phase=>window.wipKiosk?.relay?.setState({product:'EV',phase}).catch(()=>{});
const relayPhaseFor=screen=>({home:'idle',detect:'detected',align:'aligning',living:'ready',ready:'ready',charge:'charging',fault:'fault',complete:'complete'})[screen]||'idle';
const fmt=n=>{const seconds=Math.round(n);return`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};
const step=n=>`<div class="steps five">${[['01','PAIRING'],['02','FOD'],['03','LOD · LOP'],['04','PD'],['05','충전']].map((x,i)=>`${i?'<i></i>':''}<span class="${n>i?'on':''}"><b>${x[0]}</b>${x[1]}</span>`).join('')}</div>`;
const header=n=>`<header><button class="logo" data-action="admin"><b>WIP</b><span>WIRELESS POWER<br><small>CHARGING SYSTEM</small></span></button><div class="top-state"><i></i>SYSTEM ONLINE${n?`<em>${n} / 5</em>`:''}</div></header>`;
const formatBody=body=>{let v=body.replaceAll('충전 영역에서 사람 또는 동물로 판단되는 생체 신호를 감지했습니다.','차량과 충전 패드의 중심 위치가 허용 범위를 벗어났습니다.').replaceAll('사람·동물 생체 신호 감지','차량·패드 위치 불일치').replaceAll('생체가 감지되었습니다','위치 오차가 감지되었습니다').replaceAll('BIOLOGICAL OBJECT','POSITION MISALIGNMENT').replaceAll('PERSON / ANIMAL','OUT OF POSITION').replaceAll('POSITION · PRESENCE DETECTION','POSITION DETECTION').replaceAll('PD BIOLOGICAL DETECTION','PD POSITION DETECTION').replaceAll('로보택시','차량').replaceAll('자율주행 차량','차량').replaceAll('금속·생체 이물질','금속성 이물질').replaceAll('PD 생체 감지','PD 위치 감지').replaceAll('PD 생체','PD 위치').replaceAll('위치·생체','차량·패드 위치').replaceAll('차량 충전 중','무선 전력 공급 중').replaceAll('차량 충전이<br>완료되었습니다.','무선전력 공급이<br>완료되었습니다.');if(s.screen==='align')v=v.replace('SMART POSITIONING','FOD PAD SCAN').replace('충전 패드를<br>정렬하고 있습니다.','무선충전 패드를<br>검사하고 있습니다.').replace('영상처럼 차량 수신 코일과 지면 급전 코일의 중심을 맞춥니다.','차량 앞쪽 하부의 무선충전 패드 전면을 스캔합니다.');if(s.screen==='ready')v=v.replace('READY TO CHARGE','TOP VIEW POSITION CHECK').replace('안전 확인이<br>완료되었습니다.','차량과 패드의<br>위치를 확인합니다.').replace('<button class="primary wide" data-action="charge">충전 시작 ⚡</button>','<button class="primary wide analyzing-button" data-action="charge" disabled>PD 위치 분석 중…</button>');return v};
const shell=(body,n=0)=>`<div class="app">${header(n)}${formatBody(body).replaceAll('금속 및 생체 이물질 감지 영역 활성화','금속성 이물질 검출 및 위치 확인 활성화').replaceAll('무선 전력 공급 중','무선충전 진행 중')}<footer><span>AI 기반 위치 인식</span><span>금속성 이물질 검출(FOD)</span><span>무선전력 충전 시스템</span></footer></div>${s.admin?admin():''}`;
const taxi=(mode='idle')=>mode==='idle'?`<div class="taxi idle"><img src="assets/kia-pbv-hero-v2.png" alt="기아 PBV"><span class="lidar">PAIRING <b>READY</b></span></div>`:bay(({scan:'entering',aligning:'fod',living:'lod',ready:'pd',charging:'charging',hazard:`${s.scenario} hazard-bay`,completed:'completed'})[mode]||mode);
const bay=mode=>`<div class="bay-scene ${mode}"><img class="bay-bg" src="assets/charging-bay-top.png" alt="무선충전 패드"><div class="legacy-pad-mask"></div><img class="active-pad" src="assets/pha-wip-ground-pad.png" alt="PHA-WIP 급전패드"><span class="pad-rating">GA · 50 kW</span><img class="moving-car${mode==="charging"?" front-view":""}" src="${mode==="charging"?"assets/kia-pbv-front-charge.png":"assets/kia-pbv-top.png"}" alt="진입하는 기아 PBV">${mode==='charging'?'<div class="vehicle-lighting" aria-hidden="true"><i></i><i></i><span></span></div>':''}${mode==='fod'?'<div class="bay-mode fod-mode"><i></i><span><small>FOREIGN OBJECT DETECTION</small><b>FOD 금속성 이물질 검사 중</b></span><em>SCANNING</em></div>':mode==='lod'?'<div class="bay-mode living-mode"><i></i><span><small>LIVING OBJECT DETECTION · PROTECTION</small><b>LOD 감지 및 LOP 보호 확인 중</b></span><em>MONITORING</em></div>':mode==='pd'?'<div class="bay-mode pd-mode"><i></i><span><small>POSITION DETECTION</small><b>PD 차량·패드 위치 확인 중</b></span><em>ANALYZING</em></div>':''}<div class="bay-pad-scan"><i></i></div><div class="bay-target"><i></i><i></i><span>PAD CENTER</span></div>${mode==='charging'?'<div class="power-badge"><small>HIGH POWER WIRELESS CHARGING</small><b>50 kW</b></div><div class="magnetic-field"><i></i><i></i><i></i><i></i></div><div class="receiver-coil"><i></i><i></i><b>VA · RX COIL</b></div><div class="underbody-battery"><span><i></i></span><b>BATTERY</b></div><div class="energy-route"><i></i><i></i><i></i><i></i><i></i></div><div class="bay-energy"><i></i><i></i><i></i><b class="live-power">0.0 kW</b></div>':''}</div>`;
const caption=(a,b)=>`<div class="visual-caption"><b>${a}</b><span>${b}</span></div>`;
const rows=items=>`<div class="ready-list">${items.map(x=>`<span><i>${x[2]?'✓':'·'}</i><b>${x[0]}</b><em>${x[1]}</em></span>`).join('')}</div>`;
const processRows=screen=>rows(stageChecks[screen].map(x=>[x[0],s.progress>=x[3]?x[1]:x[2],s.progress>=x[3]]));
function home(){return shell(`<main class="hero pbv-hero"><div class="pbv-backdrop"></div><div class="copy"><span class="eyebrow">KIA PBV · WIP WIRELESS CHARGING</span><h1>정차하는 순간,<br><em>무선충전이 시작됩니다.</em></h1><p>차량과 충전 패드의 연결부터 감지, 위치 확인, 전력 전송까지<br>WIP 무선충전 기능을 순서대로 시연합니다.</p><button class="primary" data-action="begin">자동 시연 시작 <b>→</b></button><div class="mini feature-list"><span><b>PAIRING</b> 차량·패드 연결</span><span><b>FOD</b> 금속 이물질 감지</span><span><b>LOD</b> 생체 접근 감지</span><span><b>LOP</b> 전력 보호</span><span><b>POSITION DETECTION</b> 위치 확인</span><span><b>POWER TRANSFER</b> 무선 전력</span></div></div></main>`)}
function detect(){return shell(`<main class="stage">${step(1)}<div class="stage-grid"><section>${taxi('scan')}<div class="sensor-sweep"></div>${caption('VEHICLE PAIRING','차량과 급전패드를 하나의 충전 세션으로 연결합니다')}</section><aside><span class="eyebrow">WIP VEHICLE PAIRING</span><h2>차량과 충전 패드를<br>연결하고 있습니다.</h2><p>차량을 인식하고 통신 연결과 세션 페어링을 순서대로 확인합니다.</p>${processRows('detect')}<div class="progress"><i style="width:${s.progress}%"></i></div></aside></div></main>`,1)}
function align(){return shell(`<main class="stage">${step(2)}<div class="stage-grid"><section>${taxi('aligning')}${caption('FOREIGN OBJECT DETECTION','급전패드 영역의 금속성 이물질을 검사합니다')}</section><aside><span class="eyebrow">WIP FOD CONTROL</span><h2>급전패드 영역을<br>검사하고 있습니다.</h2><p>전력 전송 전에 패드 주변을 스캔하고 금속성 이물질 여부를 확인합니다.</p>${processRows('align')}<div class="progress"><i style="width:${s.progress}%"></i></div></aside></div></main>`,2)}
function living(){return shell(`<main class="stage">${step(3)}<div class="stage-grid"><section>${taxi('living')}<div class="safety-field living-field"><i>LOD</i><i>LOP</i><i>MONITORING</i><span>LIVING OBJECT PROTECTION</span></div>${caption('LOD · LOP SAFETY CONTROL','생체 접근을 확인하고 전력 보호 상태를 준비합니다')}</section><aside><span class="eyebrow">WIP LOD · LOP CONTROL</span><h2>생체 감지와 보호 상태를<br>확인하고 있습니다.</h2><p>살아 있는 대상의 접근 여부를 확인한 뒤 LOP 보호 시스템을 활성화합니다.</p>${processRows('living')}<div class="progress"><i style="width:${s.progress}%"></i></div></aside></div></main>`,3)}
function ready(){return shell(`<main class="stage">${step(4)}<div class="stage-grid"><section>${taxi('ready')}<div class="safety-field position-field"><i>RX</i><i>GA</i><span>POSITION TARGET</span></div>${caption('POSITION DETECTION','차량 수신부와 급전패드의 중심 위치를 확인합니다')}</section><aside><span class="eyebrow">WIP POSITION DETECTION</span><h2>차량과 패드의 위치를<br>확인하고 있습니다.</h2><p>Pairing과 안전 검사가 완료된 상태에서 마지막 위치 정렬을 확인합니다.</p>${rows([['PAIRING','VERIFIED',true],['FOD','CLEAR',true],['LOD','CLEAR',true],['LOP','ARMED',true],['PD 위치 정렬','ANALYZING',false]])}<button class="primary wide analyzing-button" data-action="charge" disabled>PD 위치 확인 중…</button></aside></div></main>`,4)}
const metric=(a,b,u,m='')=>`<div class="metric ${m}" ${m==='main'?`style="--value:${Number(b)||0}%"`:''}><span>${a}</span><strong>${b}<small>${u}</small></strong>${m==='main'?'<div class="soc-gauge"><i></i><em></em></div>':''}</div>`;
function charge(){return shell(`<main class="stage charging">${step(5)}<div class="charge-grid"><section>${taxi('charging')}${caption('PHA-WIP WIRELESS POWER TRANSFER','급전패드에서 차량 집전장치로 전력을 전송합니다')}<div class="charge-label"><i></i><span>50 kW POWER TRANSFER</span><b>ACTIVE</b></div></section><aside><div class="charge-title"><div><span class="eyebrow">PV5 LONG RANGE · 71.2 kWh · SOC 20→80%</span><h2>무선충전 진행 중</h2></div><span class="live"><i></i>LIVE</span></div><div class="metrics">${metric('SOC',Math.round(s.soc),'%','main')}${metric('이번 세션 충전량',s.energy.toFixed(1),' kWh')}${metric('충전 전력',s.power.toFixed(1),' kW')}${metric('충전 시간',fmt(s.elapsed),'')}</div><div class="safety"><div><span>SAFETY MONITOR</span><b>실시간 감지 중</b></div><span class="safe-chip"><i>✓</i>FOD 금속 이물질<b>CLEAR</b></span><span class="safe-chip"><i>✓</i>LOD 생체 접근<b>CLEAR</b></span><span class="safe-chip"><i>✓</i>LOP 전력 보호<b>ARMED</b></span><span class="safe-chip"><i>✓</i>PD 위치 감지<b>ALIGNED</b></span></div><button class="stop" data-action="stop">충전 정지</button></aside></div></main>`,5)}
const faultCopy={
  fod:{step:2,symbol:'◆',object:'METAL OBJECT',caption:'FOD METAL DETECTION',detail:'금속성 이물질 감지',code:'FOD',title:'금속성 이물질이 감지되었습니다.',body:'급전패드 영역에서 금속성 이물질을 감지했습니다.',type:'METALLIC OBJECT'},
  lod:{step:3,symbol:'●',object:'LIVING OBJECT',caption:'LOD · LOP PROTECTION',detail:'생체 접근 감지 · LOP 활성화',code:'LOP',title:'생체 접근이 감지되었습니다.',body:'살아 있는 대상의 접근을 감지해 LOP 보호 상태를 활성화했습니다.',type:'LIVING OBJECT'},
  pd:{step:4,symbol:'◎',object:'POSITION MISMATCH',caption:'PD POSITION DETECTION',detail:'차량·패드 위치 불일치',code:'PD',title:'위치 오차가 감지되었습니다.',body:'차량 수신부와 급전패드의 중심이 허용 범위를 벗어났습니다.',type:'OUT OF POSITION'}
};
function fault(){let x=faultCopy[s.scenario]||faultCopy.fod;return shell(`<main class="hazard ${s.scenario}">${step(x.step)}<div class="hazard-grid"><section>${taxi('hazard')}<div class="detect-zone"><i class="object">${x.symbol}</i><i class="ring r1"></i><i class="ring r2"></i><span>${x.object}</span></div>${caption(x.caption,x.detail)}</section><aside><span class="alarm">SAFETY PROTOCOL ACTIVE</span><div class="hazard-icon">${x.code}</div><h2>${x.title}</h2><p>${x.body}<br>전력 출력을 즉시 차단했습니다.</p><dl><div><dt>감지 유형</dt><dd>${x.type}</dd></div><div><dt>전력 출력</dt><dd>0.0 kW · DISABLED</dd></div></dl><div class="buttons"><button class="primary" data-action="retry">처음부터 다시 확인</button><button data-action="home">홈으로</button></div></aside></div></main>`,x.step)}
function complete(){return shell(`<main class="complete-screen"><div class="victory-overlay"><div class="victory-burst"><i></i><i></i><i></i></div><span>SESSION CLEAR</span><strong>충전 완료</strong><b>80<small>%</small></b><em>50 kW 무선전력 공급이 완료되었습니다</em></div><div class="complete-scene">${taxi('completed')}<div class="complete-rings"><i></i><i></i><i></i><b>✓</b></div></div><aside><span class="eyebrow">CHARGING SESSION COMPLETE</span><h2>무선전력 공급이<br>완료되었습니다.</h2><p>PV5 71.2 kWh 기준 SOC 20→80% 시뮬레이션이<br>안전하게 종료되었습니다.</p><div class="complete-data">${metric('최종 SOC',chargeConfig.targetSocPercent,'%')}${metric('이번 세션 충전량',targetEnergyKWh.toFixed(1),' kWh')}${metric('충전 시간',fmt(targetElapsedSeconds),'')}</div><button class="primary wide" data-action="home">처음 화면으로</button></aside></main>`,4)}
function admin(){return `<div class="overlay"><div class="admin"><button class="close" data-action="close">×</button><span>OPERATOR CONSOLE</span><h2>시연 시나리오</h2><p>각 오류는 해당 검사 단계에서 전력 인가 전에 차단됩니다.</p><div class="choices">${[['normal','정상 흐름','PAIRING → POWER'],['fod','FOD 감지','금속성 이물질'],['lod','LOD · LOP','생체 접근 · 보호'],['pd','PD 오류','위치 불일치']].map(x=>`<button class="${s.scenario===x[0]?'selected':''}" data-scenario="${x[0]}"><i></i><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><button class="primary wide" data-action="run">선택 시나리오 실행</button></div></div>`}
function render(){let f={home,detect,align,living,ready,charge,fault,complete}[s.screen]||home;root.innerHTML=f();if(s.screen==='ready'&&!s.pdTimer){s.pdTimer=setTimeout(()=>{s.pdTimer=null;if(s.screen==='ready'){s.scenario==='pd'?showFault():finishPd()}},demoTiming.pdMs)}}
function clear(){clearInterval(s.timer);clearTimeout(s.timer);clearTimeout(s.pdTimer);clearTimeout(s.autoChargeTimer);s.timer=null;s.pdTimer=null;s.autoChargeTimer=null}
function restartLoop(){clear();s.screen='home';s.scenario='normal';s.progress=0;relay('idle');render();s.timer=setTimeout(()=>{if(s.screen==='home')animate('detect','align')},demoTiming.homeMs)}
function showFault(){clear();s.screen='fault';relay('fault');render()}
function finishPd(){let btn=root.querySelector('[data-action="charge"]'),badge=root.querySelector('.pd-mode'),items=root.querySelectorAll('.ready-list>span');if(items.length){let item=items[items.length-1],icon=item.querySelector('i'),status=item.querySelector('em');if(icon)icon.textContent='✓';if(status)status.textContent='ALIGNED'}if(btn){btn.disabled=false;btn.classList.remove('analyzing-button');btn.classList.add('ready-button');btn.innerHTML='무선 전력 공급 준비 ✓'}if(badge){badge.classList.add('complete-check');let title=badge.querySelector('b'),status=badge.querySelector('em');if(title)title.textContent='PD 차량·패드 위치 확인 완료';if(status)status.textContent='ALIGNED'}s.autoChargeTimer=setTimeout(()=>{s.autoChargeTimer=null;if(s.screen==='ready'&&s.scenario==='normal')startCharge()},demoTiming.pdCompleteMs)}
function updateStageProgress(){let checks=stageChecks[s.screen],bar=root.querySelector('.progress i');if(bar)bar.style.width=`${s.progress}%`;if(!checks)return;let items=root.querySelectorAll('.ready-list>span');checks.forEach((x,i)=>{let item=items[i];if(!item)return;let done=s.progress>=x[3],icon=item.querySelector('i'),status=item.querySelector('em');if(icon)icon.textContent=done?'✓':'·';if(status)status.textContent=done?x[1]:x[2]});let badge=root.querySelector('.bay-mode');if(badge&&s.progress>=90){badge.classList.add('complete-check');let status=badge.querySelector('em'),title=badge.querySelector('b');if(status)status.textContent=s.screen==='living'?'ARMED':'CLEAR';if(title)title.textContent=s.screen==='living'?'LOD 확인 · LOP 보호 준비 완료':'FOD 금속성 이물질 없음'}}
function animate(screen,next,ms=stageDuration[screen]||6000){clear();s.screen=screen;s.progress=0;relay(relayPhaseFor(screen));render();let started=performance.now();s.timer=setInterval(()=>{s.progress=Math.min(100,(performance.now()-started)/ms*100);updateStageProgress();let fault=(screen==='align'&&s.scenario==='fod')||(screen==='living'&&s.scenario==='lod');if(fault&&s.progress>=65){showFault();return}if(s.progress>=100){clearInterval(s.timer);s.timer=setTimeout(()=>{s.timer=null;if(next==='ready'){s.screen='ready';relay('ready');render()}else animate(next,next==='align'?'living':'ready')},demoTiming.stageCompleteMs)}},100)}
function startCharge(){clear();Object.assign(s,{screen:'charge',soc:chargeConfig.startSocPercent,power:0,energy:0,elapsed:0});relay('charging');render();const started=performance.now(),duration=chargeConfig.demoDurationMs,ramp=chargeConfig.powerReadyMs;const update=()=>{const ms=performance.now()-started,ratio=Math.min(1,ms/duration),chargeRatio=Math.max(0,Math.min(1,(ms-ramp)/(duration-ramp)));Object.assign(s,chargeSample(chargeRatio));s.power=ms<ramp?chargeConfig.nominalPowerKw*(ms/ramp):chargeConfig.nominalPowerKw;const values=root.querySelectorAll('.metrics .metric strong');if(values[0])values[0].innerHTML=`${Math.round(s.soc)}<small>%</small>`;if(values[1])values[1].innerHTML=`${s.energy.toFixed(1)}<small> kWh</small>`;if(values[2])values[2].innerHTML=`${s.power.toFixed(1)}<small> kW</small>`;if(values[3])values[3].textContent=fmt(s.elapsed);const main=root.querySelector('.metric.main'),gauge=root.querySelector('.soc-gauge i'),battery=root.querySelector('.underbody-battery span i'),livePower=root.querySelector('.live-power'),title=root.querySelector('.charge-title h2'),label=root.querySelector('.charge-label b');const gaugePercent=(s.soc-chargeConfig.startSocPercent)/(chargeConfig.targetSocPercent-chargeConfig.startSocPercent)*100;if(main)main.style.setProperty('--value',`${gaugePercent}%`);if(gauge)gauge.style.width=`${gaugePercent}%`;if(battery)battery.style.height=`${gaugePercent}%`;if(livePower)livePower.textContent=`${s.power.toFixed(1)} kW`;if(title)title.textContent=ms<ramp?'50 kW 전력 준비 중':'무선충전 진행 중';if(label)label.textContent=ms<ramp?'POWER RAMP-UP':'50 kW ACTIVE';if(ratio>=1){clear();Object.assign(s,chargeSample(1),{power:chargeConfig.nominalPowerKw,screen:'complete'});relay('complete');render();s.timer=setTimeout(()=>{if(s.screen==='complete')restartLoop()},demoTiming.completeMs)}};s.timer=setInterval(update,50);update()}
root.addEventListener('click',e=>{let el=e.target.closest('[data-action],[data-scenario]');if(!el)return;if(el.dataset.scenario){s.scenario=el.dataset.scenario;render();return}let a=el.dataset.action;if(a==='admin'){if(++s.taps>=5){s.taps=0;s.admin=true;render()}return}if(a==='begin'){animate('detect','align');return}if(a==='charge'){startCharge();return}if(a==='stop'){s.scenario='fod';showFault();return}if(a==='retry'){s.scenario='normal';animate('detect','align');return}if(a==='home'){restartLoop();return}if(a==='close'){s.admin=false;render();return}if(a==='run'){s.admin=false;animate('detect','align')}});
render();s.timer=setTimeout(()=>{if(s.screen==='home')animate('detect','align')},demoTiming.homeMs);
})();
