(() => {
  'use strict';

  const root = document.querySelector('#app');
  const STORAGE_KEY = 'wip-kiosk-settings-v2';
  const screens = ['home', 'detect', 'align', 'ready', 'charge', 'complete', 'tech', 'brand', 'fault'];
  const defaults = { lang: 'ko', mode: 'DEMO', product: 'EV', scenario: 'normal', speed: 1, startSoc: 38, targetSoc: 80, idleSeconds: 120 };
  const saved = (() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } })();

  const state = {
    ...defaults, ...saved, screen: 'home', admin: false, adminPage: 'control', brandSector: 'passenger', running: false,
    soc: saved.startSoc || defaults.startSoc, elapsed: 0, energy: 0, power: 0, efficiency: 93.4,
    temperature: 27.8, lateral: 12, forward: 18, gap: 205, checks: 0, fault: null,
    timer: null, transition: null, idleTimer: null, brandTaps: 0, brandTapTimer: null
  };

  const ko = {
    online:'시스템 정상', demo:'DEMO MODE', live:'LIVE MODE', navHome:'홈', navExperience:'충전 체험', navTech:'핵심 기술', navBrand:'WIP',
    heroTag:'22 kW 무선 EV 충전', heroTitle:'머무는 순간,<br><em>충전이 시작됩니다.</em>', heroDesc:'케이블 없이 더 깨끗하고 직관적으로. 차량과 충전 패드가 서로를 인식해 안전하고 효율적인 에너지 흐름을 완성합니다.',
    start:'체험 시작', explore:'기술 알아보기', cable:'케이블 제로', efficiency:'최대 효율 93.4%', safety:'다중 안전 제어',
    detectTag:'VEHICLE DETECTION', detectTitle:'차량을 인식하고 있습니다', detectDesc:'차량과 지면 패드의 위치, 통신 상태를 확인합니다.', detected:'차량 감지', link:'보안 통신', preparing:'시스템 준비',
    alignTag:'SMART POSITIONING', alignTitle:'충전 위치를 정렬합니다', alignDesc:'정확한 전력 전송을 위해 차량을 최적 위치로 안내합니다.', lateral:'좌우 정렬', forward:'전후 정렬', gap:'패드 간 거리', analyzing:'분석 중', optimal:'최적',
    readyTag:'READY TO CHARGE', readyTitle:'안전 확인이 완료되었습니다', readyDesc:'모든 충전 조건이 정상입니다. 터치하면 무선 충전이 시작됩니다.', alignment:'위치 정렬', object:'이물질 감지', communication:'차량 통신', temperature:'패드 온도', clear:'없음', normal:'정상', startCharge:'충전 시작',
    charging:'무선 충전 중', battery:'배터리 충전량', power:'충전 전력', delivered:'전달 에너지', elapsed:'경과 시간', remaining:'예상 남은 시간', safetyState:'실시간 안전 상태', emergency:'비상 회로', active:'활성', stop:'안전 정지',
    complete:'충전이 완료되었습니다', completeDesc:'깨끗한 에너지가 차량에 안전하게 전달되었습니다. 케이블 없이 더 자연스러운 이동을 경험하세요.', again:'다시 체험하기', carbon:'예상 탄소 저감', session:'충전 세션',
    techTag:'HOW IT WORKS', techTitle:'보이지 않는 에너지를<br>더 안전하고 스마트하게', techDesc:'정렬부터 전력 전송, 안전 제어까지 하나의 지능형 플랫폼으로 연결합니다.',
    tech1:'자동 위치 정렬', tech1d:'차량과 패드의 위치를 실시간 감지해 최적 전력 전달 지점으로 안내합니다.', tech2:'고효율 전력 전송', tech2d:'송·수신 패드 사이에 안정적인 자기장을 형성해 에너지를 전달합니다.', tech3:'다중 안전 제어', tech3d:'이물질, 온도, 통신을 지속 감시하고 이상 시 즉시 출력을 차단합니다.',
    brandTag:'ABOUT WIP', brandTitle:'전력과 이동을<br>자연스럽게 연결합니다', brandDesc:'WIP는 무선전력 기술로 충전의 번거로움을 없애고, 사람과 모빌리티가 더 깨끗하게 움직이는 환경을 설계합니다.', solutions:'APPLICATION PLATFORM', passenger:'승용 모빌리티', commercial:'상용 차량', robotics:'로봇 · AMR', passengerD:'주차하는 순간 충전이 시작되는 일상형 EV 무선충전 경험', commercialD:'물류·버스·특수차량의 운행 동선을 멈추지 않는 자동 충전 인프라', roboticsD:'정밀 정렬과 자동 충전으로 24시간 운영을 지원하는 무인 전력 플랫폼', scalable:'하나의 전력 플랫폼, 다양한 모빌리티', scalableD:'차량과 운영 환경에 맞춰 송수신 패드, 전력, 통신 방식을 확장할 수 있습니다.',
    faultTitle:'안전을 위해 충전을 정지했습니다', retry:'안전 확인 후 재시도', home:'홈으로', faultFod:'충전 패드 주변에서 이물질이 감지되었습니다.', faultComm:'차량과 충전 시스템의 통신이 끊어졌습니다.', faultAlign:'차량이 충전 가능 범위를 벗어났습니다.', faultEmergency:'비상 정지 신호가 입력되었습니다.',
    admin:'전시 운영 관리자', control:'시나리오', settings:'설정', normalScenario:'정상 충전', alignFail:'정렬 실패', fod:'이물질 감지', commFail:'통신 오류', eStop:'비상 정지', run:'시나리오 실행', reset:'전체 초기화', quit:'앱 종료', quitConfirm:'전시용 소프트웨어를 종료할까요?', browserQuit:'브라우저 미리보기에서는 창을 직접 닫아주세요.', close:'닫기', mode:'데이터 모드', demoSpeed:'데모 속도', startSoc:'시작 SOC', targetSoc:'목표 SOC', idle:'자동 복귀', seconds:'초', language:'표시 언어', liveNote:'LIVE MODE는 장비 어댑터 연결 전까지 안전한 대기 데이터를 표시합니다.', hidden:'로고를 5회 터치하면 관리자 메뉴가 열립니다.'
  };
  const en = {
    online:'SYSTEM ONLINE', demo:'DEMO MODE', live:'LIVE MODE', navHome:'Home', navExperience:'Experience', navTech:'Technology', navBrand:'WIP',
    heroTag:'22 kW WIRELESS EV CHARGING', heroTitle:'Park naturally.<br><em>Charge instantly.</em>', heroDesc:'Cleaner and more intuitive without cables. The vehicle and charging pad recognize each other to create a safe, efficient flow of energy.',
    start:'Start Experience', explore:'Explore Technology', cable:'Zero Cables', efficiency:'Up to 93.4% Efficiency', safety:'Layered Safety',
    detectTag:'VEHICLE DETECTION', detectTitle:'Detecting your vehicle', detectDesc:'Checking vehicle position, ground pad and secure communication.', detected:'Vehicle detected', link:'Secure link', preparing:'System ready',
    alignTag:'SMART POSITIONING', alignTitle:'Aligning for charging', alignDesc:'Guiding the vehicle to the optimal position for precise power transfer.', lateral:'Lateral alignment', forward:'Longitudinal alignment', gap:'Pad gap', analyzing:'Analyzing', optimal:'Optimal',
    readyTag:'READY TO CHARGE', readyTitle:'Safety checks complete', readyDesc:'Every charging condition is normal. Touch to begin wireless charging.', alignment:'Alignment', object:'Foreign object', communication:'Vehicle link', temperature:'Pad temperature', clear:'Clear', normal:'Normal', startCharge:'Start Charging',
    charging:'Wireless Charging', battery:'Battery state', power:'Charging power', delivered:'Energy delivered', elapsed:'Elapsed time', remaining:'Time remaining', safetyState:'Live safety status', emergency:'Emergency circuit', active:'Active', stop:'Safety Stop',
    complete:'Charging Complete', completeDesc:'Clean energy was delivered safely to the vehicle. Experience a more natural way to move, without cables.', again:'Experience Again', carbon:'Estimated CO₂ saved', session:'Charge session',
    techTag:'HOW IT WORKS', techTitle:'Invisible energy.<br>Safer and smarter.', techDesc:'Alignment, power transfer and safety control connected through one intelligent platform.',
    tech1:'Auto Alignment', tech1d:'Detects vehicle and pad positions in real time and guides the optimal transfer point.', tech2:'Efficient Transfer', tech2d:'Creates a stable magnetic field between transmitting and receiving pads.', tech3:'Layered Safety', tech3d:'Continuously monitors objects, temperature and communication, stopping output instantly.',
    brandTag:'ABOUT WIP', brandTitle:'Connecting power<br>and mobility naturally', brandDesc:'WIP removes the friction of charging with wireless power and designs cleaner environments for people and mobility.', solutions:'APPLICATION PLATFORM', passenger:'Passenger Mobility', commercial:'Commercial Fleets', robotics:'Robotics · AMR', passengerD:'Everyday wireless EV charging that begins naturally when the vehicle parks.', commercialD:'Automated charging infrastructure that keeps logistics, buses and fleets moving.', roboticsD:'An unattended power platform supporting 24/7 operation with precise auto alignment.', scalable:'One power platform. Many ways to move.', scalableD:'Transmission pads, power levels and communication can scale to each vehicle and site.',
    faultTitle:'Charging stopped for safety', retry:'Check Safety & Retry', home:'Return Home', faultFod:'A foreign object was detected near the charging pad.', faultComm:'Communication between the vehicle and charger was interrupted.', faultAlign:'The vehicle moved outside the chargeable alignment range.', faultEmergency:'An emergency stop signal was received.',
    admin:'Exhibition Admin', control:'Scenarios', settings:'Settings', normalScenario:'Normal Charge', alignFail:'Alignment Failure', fod:'Foreign Object', commFail:'Communication Fault', eStop:'Emergency Stop', run:'Run Scenario', reset:'Reset All', quit:'Quit App', quitConfirm:'Quit the exhibition software?', browserQuit:'Close the browser window to exit preview mode.', close:'Close', mode:'Data Mode', demoSpeed:'Demo Speed', startSoc:'Start SOC', targetSoc:'Target SOC', idle:'Auto Return', seconds:'sec', language:'Language', liveNote:'LIVE MODE displays safe standby data until a device adapter is connected.', hidden:'Tap the logo five times to open the admin panel.'
  };
  const t = () => state.lang === 'ko' ? ko : en;
  const persist = () => localStorage.setItem(STORAGE_KEY, JSON.stringify({ lang:state.lang, mode:state.mode, product:state.product, scenario:state.scenario, speed:state.speed, startSoc:state.startSoc, targetSoc:state.targetSoc, idleSeconds:state.idleSeconds }));
  const fmt = s => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
  const icon = name => `<svg aria-hidden="true" viewBox="0 0 24 24"><use href="#i-${name}"></use></svg>`;
  const icons = `<svg class="svg-defs" aria-hidden="true"><defs>
    <symbol id="i-home" viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z"/></symbol><symbol id="i-bolt" viewBox="0 0 24 24"><path d="m13.5 2-8 12H12l-1.5 8 8-12H12z"/></symbol>
    <symbol id="i-tech" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M4.9 4.9 7 7m10 10 2.1 2.1M19.1 4.9 17 7M7 17l-2.1 2.1"/></symbol><symbol id="i-leaf" viewBox="0 0 24 24"><path d="M20 4C11 4 5 8 5 15c0 3 2 5 5 5 7 0 10-8 10-16Z"/><path d="M4 21c2-6 7-9 12-12"/></symbol>
    <symbol id="i-check" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></symbol><symbol id="i-car" viewBox="0 0 24 24"><path d="m5 11 2-5h10l2 5 2 2v5h-3v-2H6v2H3v-5z"/><path d="M7 13h.01M17 13h.01"/></symbol>
    <symbol id="i-signal" viewBox="0 0 24 24"><path d="M5 12.5a10 10 0 0 1 14 0M8 16a6 6 0 0 1 8 0m-4 4h.01"/></symbol><symbol id="i-shield" viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.5 8-8 10-4.5-2-8-5-8-10V6z"/><path d="m8.5 12 2 2 5-5"/></symbol>
    <symbol id="i-arrow" viewBox="0 0 24 24"><path d="M5 12h14m-5-5 5 5-5 5"/></symbol><symbol id="i-x" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></symbol>
  </defs></svg>`;

  function header() { const c=t(); return `<header class="topbar"><button class="brand" data-action="brandTap" aria-label="WIP"><b>WIP</b><span><strong>WiPowerOne</strong><small>Wireless Power, Naturally.</small></span></button><div class="system"><div class="product-switch" aria-label="Demo product"><button class="${state.product==='EV'?'active':''}" data-product="EV">EV</button><button class="${state.product==='AMR'?'active':''}" data-product="AMR">AMR</button></div><span class="status"><i></i>${c.online}</span><span class="mode">${state.mode==='DEMO'?c.demo:c.live}</span><button class="language" data-action="lang">${state.lang==='ko'?'EN':'KO'}</button></div></header>`; }
  function nav(active) { const c=t(); return `<nav class="nav">${[['home','home',c.navHome],['experience','bolt',c.navExperience],['tech','tech',c.navTech],['brand','leaf',c.navBrand]].map(([key,ic,label])=>`<button class="${active===key?'active':''}" data-nav="${key}">${icon(ic)}<span>${label}</span></button>`).join('')}</nav>`; }
  function shell(body, active='home', dark=false) { return `${icons}<div class="kiosk product-${state.product.toLowerCase()} ${dark?'is-dark':''}">${header()}<main class="viewport">${body}</main>${nav(active)}</div>${state.admin?admin():''}`; }
  function button(label, action, secondary=false) { return `<button class="cta ${secondary?'secondary':''}" data-action="${action}">${label}${!secondary?icon('arrow'):''}</button>`; }
  function vehicleVisual(compact=false) { return `<div class="vehicle-scene ${compact?'compact':''}"><div class="orbital o1"></div><div class="orbital o2"></div><div class="power-beam"></div><div class="ground-pad"><i></i><i></i></div><div class="vehicle"><span class="glass"></span><span class="light l"></span><span class="light r"></span><b>${state.product==='AMR'?'AMR':'WIP'}</b></div><span class="energy-chip chip-a">${state.product==='AMR'?'3.3':'22.0'} <small>kW</small></span><span class="energy-chip chip-b">93.4 <small>%</small></span></div>`; }
  function productCopy(){
    if(state.product==='EV') return null;
    return state.lang==='ko'
      ? { tag:'SMART AMR WIRELESS CHARGING', title:'멈추지 않는 운영,<br><em>자동으로 충전합니다.</em>', desc:'AMR이 충전 위치에 도착하면 정렬과 안전 상태를 확인하고 무인 충전을 시작합니다.', start:'AMR 충전 체험' }
      : { tag:'SMART AMR WIRELESS CHARGING', title:'Always moving.<br><em>Automatically charging.</em>', desc:'When the AMR reaches its station, alignment and safety checks start unattended charging.', start:'Start AMR Experience' };
  }
  function home() { const c=t(); const p=productCopy(); return shell(`<section class="hero"><div class="hero-copy"><span class="eyebrow">${p?.tag||c.heroTag}</span><h1>${p?.title||c.heroTitle}</h1><p>${p?.desc||c.heroDesc}</p><div class="actions">${button(p?.start||c.start,'start')}${button(c.explore,'tech',true)}</div><div class="proof"><span>${icon('bolt')}<b>${c.cable}</b></span><span>${icon('leaf')}<b>${c.efficiency}</b></span><span>${icon('shield')}<b>${c.safety}</b></span></div></div>${vehicleVisual()}</section>`,'home'); }
  function stageHead(tag,title,desc,step){ return `<div class="stage-head"><div><span class="eyebrow">${tag}</span><h2>${title}</h2><p>${desc}</p></div><b class="step">${step} / 04</b></div>`; }
  function detect() { const c=t(); return shell(`<section class="stage">${stageHead(c.detectTag,c.detectTitle,c.detectDesc,'01')}<div class="detect-layout"><div class="scanner">${vehicleVisual(true)}<span class="scan"></span></div><div class="check-stack">${checkCard('car',c.detected,state.checks>0)}${checkCard('signal',c.link,state.checks>1)}${checkCard('shield',c.preparing,state.checks>2)}</div></div></section>`,'experience'); }
  function checkCard(ic,label,done){ return `<div class="check-card ${done?'done':''}">${icon(ic)}<div><span>${label}</span><strong>${done?t().normal:t().analyzing}</strong></div><i>${done?icon('check'):''}</i></div>`; }
  function metric(label,value,percent){ return `<div class="metric"><div><span>${label}</span><b>${percent>=96?t().optimal:t().analyzing}</b></div><strong>${value}</strong><div class="bar"><i style="width:${percent}%"></i></div></div>`; }
  function align() { const c=t(); const p=Math.min(100,(state.lateral+state.forward)/2); return shell(`<section class="stage">${stageHead(c.alignTag,c.alignTitle,c.alignDesc,'02')}<div class="align-layout"><div class="top-view"><div class="target"></div><div class="top-vehicle" style="--dx:${(100-state.lateral)*.22}px;--dy:${(100-state.forward)*.28}px"><span></span><b>${state.product==='AMR'?'AMR':'WIP'}</b></div><i class="scan"></i><span class="alignment-score">${Math.round(p)}<small>%</small></span></div><div class="metrics">${metric(c.lateral,`${Math.round(state.lateral)}%`,state.lateral)}${metric(c.forward,`${Math.round(state.forward)}%`,state.forward)}${metric(c.gap,`${Math.round(state.gap)} mm`,Math.min(100,state.forward))}</div></div></section>`,'experience'); }
  function ready() { const c=t(); return shell(`<section class="stage">${stageHead(c.readyTag,c.readyTitle,c.readyDesc,'03')}<div class="ready-layout"><div class="ready-visual"><div class="ready-ring">${icon('check')}</div><div class="ready-car">${icon('car')}</div><div class="ready-pad"></div></div><div class="ready-panel">${statusRow(c.alignment,'100%',true)}${statusRow(c.object,c.clear,true)}${statusRow(c.communication,c.normal,true)}${statusRow(c.temperature,'28.4 °C',true)}${button(c.startCharge,'charge')}</div></div></section>`,'experience'); }
  function statusRow(label,value,ok){ return `<div class="status-row"><span>${label}</span><b>${ok?icon('check'):''}${value}</b></div>`; }
  function charge() { const c=t(); const remain=Math.max(0,Math.ceil((state.targetSoc-state.soc)*6/state.speed)); const rated=state.product==='AMR'?'3.3':'22'; return shell(`<section class="charging"><div class="charge-primary"><div class="charge-head"><div><span class="eyebrow">${rated} kW ${state.product} WIRELESS POWER</span><h2>${c.charging}</h2></div><span class="live"><i></i>LIVE</span></div><div class="soc-ring" style="--soc:${state.soc}"><div><strong>${Math.round(state.soc)}<small>%</small></strong><span>${c.battery}</span></div></div><div class="energy-flow"><i></i><i></i><i></i><span>${icon('car')}</span></div></div><aside class="charge-data"><div class="data-grid">${data(c.power,`${state.power.toFixed(1)} kW`)}${data(c.delivered,`${state.energy.toFixed(2)} kWh`)}${data(c.efficiency,`${state.efficiency.toFixed(1)}%`)}${data(c.temperature,`${state.temperature.toFixed(1)} °C`)}${data(c.elapsed,fmt(state.elapsed))}${data(c.remaining,fmt(remain))}</div><div class="safety-panel"><h3>${c.safetyState}</h3>${statusRow(c.object,c.clear,true)}${statusRow(c.alignment,c.normal,true)}${statusRow(c.communication,c.normal,true)}${statusRow(c.emergency,c.active,true)}</div>${button(c.stop,'stop',true)}</aside></section>`,'experience',true); }
  function data(label,value){ return `<div class="data"><span>${label}</span><strong>${value}</strong></div>`; }
  function complete() { const c=t(); return shell(`<section class="complete"><div class="success">${icon('check')}</div><span class="eyebrow">SESSION COMPLETE</span><h2>${c.complete}</h2><p>${c.completeDesc}</p><div class="results">${data(c.delivered,`${Math.max(state.energy,2.8).toFixed(2)} kWh`)}${data(c.efficiency,`${state.efficiency.toFixed(1)}%`)}${data(c.carbon,`${Math.max(state.energy*.42,1.2).toFixed(1)} kg`)}</div>${button(c.again,'restart')}</section>`,'experience'); }
  function tech() { const c=t(); return shell(`<section class="info-page"><div class="info-intro"><span class="eyebrow">${c.techTag}</span><h2>${c.techTitle}</h2><p>${c.techDesc}</p></div><div class="tech-cards">${techCard('01','car',c.tech1,c.tech1d)}${techCard('02','bolt',c.tech2,c.tech2d)}${techCard('03','shield',c.tech3,c.tech3d)}</div><div class="platform"><div><b>WIP Wireless Power Platform</b><span>EV · COMMERCIAL · ROBOTICS · AMR</span></div><div class="pulse-line"><i></i></div></div></section>`,'tech'); }
  function techCard(n,ic,title,desc){ return `<article><span>${n}</span><i>${icon(ic)}</i><h3>${title}</h3><p>${desc}</p></article>`; }
  function brand() { const c=t(); const sectors={passenger:[c.passenger,c.passengerD,'EV'],commercial:[c.commercial,c.commercialD,'FLEET'],robotics:[c.robotics,c.roboticsD,'AMR']}; const selected=sectors[state.brandSector]; return shell(`<section class="brand-page"><div class="brand-story"><span class="eyebrow">${c.brandTag}</span><h2>${c.brandTitle}</h2><p>${c.brandDesc}</p><div class="brand-fact"><strong>22 kW</strong><span>WIRELESS POWER</span><strong>93.4%</strong><span>TRANSFER EFFICIENCY</span></div></div><div class="brand-solutions"><span class="eyebrow">${c.solutions}</span><div class="applications">${Object.entries(sectors).map(([key,item])=>`<button class="${state.brandSector===key?'active':''}" data-sector="${key}">${item[0]}</button>`).join('')}</div><article class="sector-card"><small>${selected[2]} SOLUTION</small><h3>${selected[0]}</h3><p>${selected[1]}</p><div class="sector-visual"><i></i><i></i><b>WIP</b></div></article><div class="scale-note"><b>${c.scalable}</b><span>${c.scalableD}</span></div></div></section>`,'brand',true); }
  function fault() { const c=t(); const desc={fod:c.faultFod,comm:c.faultComm,align:c.faultAlign,emergency:c.faultEmergency}[state.fault]||c.faultFod; return shell(`<section class="fault"><div class="fault-icon">!</div><span class="eyebrow">SAFETY PROTOCOL ACTIVE</span><h2>${c.faultTitle}</h2><p>${desc}</p><div class="fault-code">${(state.fault||'fod').toUpperCase()} / OUTPUT DISABLED</div><div class="actions">${button(c.retry,'retry')}${button(c.home,'goHome',true)}</div></section>`,'experience'); }

  function admin(){ const c=t(); const scenarios=[['normal',c.normalScenario],['align',c.alignFail],['fod',c.fod],['comm',c.commFail],['emergency',c.eStop]]; return `<div class="admin-overlay"><section class="admin-modal"><header><div><span>OPERATOR CONSOLE</span><h2>${c.admin}</h2></div><button data-action="adminClose">${icon('x')}</button></header><div class="admin-tabs"><button class="${state.adminPage==='control'?'active':''}" data-admin-page="control">${c.control}</button><button class="${state.adminPage==='settings'?'active':''}" data-admin-page="settings">${c.settings}</button></div>${state.adminPage==='control'?`<div class="scenario-grid">${scenarios.map(([v,l])=>`<button class="${state.scenario===v?'active':''}" data-scenario="${v}"><i></i><b>${l}</b><small>${v.toUpperCase()}</small></button>`).join('')}</div><div class="admin-actions">${button(c.run,'runScenario')}<button class="reset" data-action="reset">${c.reset}</button><button class="quit" data-action="quitApp">${c.quit}</button></div>`:`<div class="settings-grid"><label><span>${c.mode}</span><select data-setting="mode"><option value="DEMO" ${state.mode==='DEMO'?'selected':''}>DEMO MODE</option><option value="LIVE" ${state.mode==='LIVE'?'selected':''}>LIVE MODE</option></select></label><label><span>${c.language}</span><select data-setting="lang"><option value="ko" ${state.lang==='ko'?'selected':''}>한국어</option><option value="en" ${state.lang==='en'?'selected':''}>English</option></select></label>${range(c.demoSpeed,'speed',.5,3,.5,state.speed,'×')}${range(c.startSoc,'startSoc',10,70,1,state.startSoc,'%')}${range(c.targetSoc,'targetSoc',60,100,1,state.targetSoc,'%')}${range(c.idle,'idleSeconds',30,300,10,state.idleSeconds,` ${c.seconds}`)}</div><p class="live-note">${c.liveNote}</p>`}</section></div>`; }
  function range(label,key,min,max,step,value,suffix){ return `<label class="range"><span>${label}<b>${value}${suffix}</b></span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-setting="${key}"></label>`; }

  function clearTimers(){ clearInterval(state.timer); clearTimeout(state.transition); state.timer=null; state.transition=null; }
  function setRelay(phase){ window.wipKiosk?.relay?.setState({product:state.product,phase}).catch(()=>{}); }
  function resetIdle(){ clearTimeout(state.idleTimer); if(state.screen!=='home'&&!state.admin) state.idleTimer=setTimeout(()=>go('home'),state.idleSeconds*1000); }
  function go(screen){ clearTimers(); state.screen=screens.includes(screen)?screen:'home'; if(screen==='home'){state.running=false;state.fault=null;setRelay('idle');} render(); resetIdle(); }
  function startFlow(){ setRelay('detected'); if(state.mode==='LIVE'){ state.screen='detect'; state.checks=0; render(); return; } state.running=true; state.checks=0; go('detect'); let tick=0; state.timer=setInterval(()=>{tick++;state.checks=Math.min(3,Math.floor(tick/5));render();if(tick>=18){clearTimers();beginAlign();}},100/state.speed); }
  function beginAlign(){ setRelay('aligning'); state.lateral=14;state.forward=20;state.gap=205;go('align');state.timer=setInterval(()=>{state.lateral=Math.min(100,state.lateral+1.7*state.speed);state.forward=Math.min(100,state.forward+1.5*state.speed);state.gap=Math.max(145,state.gap-1.1*state.speed);if(state.scenario==='align'&&state.lateral>70){triggerFault('align');return;}render();if(state.lateral>=100&&state.forward>=100){clearTimers();state.transition=setTimeout(()=>{setRelay('ready');go('ready');},450);}},70); }
  function startCharge(){ setRelay('charging'); state.soc=Number(state.startSoc);state.elapsed=0;state.energy=0;state.power=state.product==='AMR'?3.3:21.8;state.temperature=28.4;go('charge');state.timer=setInterval(()=>{state.elapsed+=1*state.speed;state.soc=Math.min(state.targetSoc,state.soc+.075*state.speed);state.energy+=state.power/3600*state.speed;const rated=state.product==='AMR'?3.3:21.7;state.power=rated+Math.sin(state.elapsed/5)*(state.product==='AMR'?.08:.3);state.efficiency=93.3+Math.sin(state.elapsed/8)*.2;state.temperature=Math.min(36.5,state.temperature+.012*state.speed);if(state.scenario!=='normal'&&state.elapsed>8){triggerFault(state.scenario);return;}if(state.soc>=state.targetSoc){clearTimers();setRelay('complete');go('complete');return;}render();},250); }
  function triggerFault(type){clearTimers();setRelay('fault');state.fault=type;go('fault');}
  function resetAll(){Object.assign(state,{...defaults,screen:'home',admin:false,running:false,soc:defaults.startSoc,elapsed:0,energy:0,fault:null});localStorage.removeItem(STORAGE_KEY);go('home');}
  function render(){ const views={home,detect,align,ready,charge,complete,tech,brand,fault}; root.innerHTML=(views[state.screen]||home)(); }

  root.addEventListener('click',e=>{ const btn=e.target.closest('button,[data-nav],[data-scenario],[data-admin-page],[data-sector],[data-product]'); if(!btn)return; resetIdle(); if(btn.dataset.product){state.product=btn.dataset.product;persist();setRelay('idle');go('home');return;} const nav=btn.dataset.nav; if(nav){ if(nav==='experience')startFlow();else go(nav);return; } if(btn.dataset.sector){state.brandSector=btn.dataset.sector;render();return;} if(btn.dataset.scenario){state.scenario=btn.dataset.scenario;persist();render();return;} if(btn.dataset.adminPage){state.adminPage=btn.dataset.adminPage;render();return;} const a=btn.dataset.action; if(!a)return; ({start:startFlow,tech:()=>go('tech'),charge:startCharge,stop:()=>triggerFault('emergency'),restart:startFlow,retry:()=>{state.scenario='normal';beginAlign();},goHome:()=>go('home'),adminClose:()=>{state.admin=false;render();resetIdle();},runScenario:()=>{state.admin=false;state.scenario==='normal'?startFlow():(state.scenario==='align'?beginAlign():(go('charge'),state.transition=setTimeout(()=>triggerFault(state.scenario),900)));},reset:resetAll,quitApp:()=>{if(!confirm(t().quitConfirm))return;if(window.wipKiosk?.quit)window.wipKiosk.quit();else alert(t().browserQuit);},lang:()=>{state.lang=state.lang==='ko'?'en':'ko';persist();render();},brandTap:()=>{state.brandTaps++;clearTimeout(state.brandTapTimer);state.brandTapTimer=setTimeout(()=>state.brandTaps=0,1800);if(state.brandTaps>=5){state.brandTaps=0;state.admin=true;clearTimeout(state.idleTimer);render();}}}[a]||(()=>{}))(); });
  root.addEventListener('input',e=>{const key=e.target.dataset.setting;if(!key)return;let value=e.target.value;if(['speed','startSoc','targetSoc','idleSeconds'].includes(key))value=Number(value);state[key]=value;if(key==='startSoc'&&state.targetSoc<=value)state.targetSoc=Math.min(100,value+10);persist();render();});
  document.addEventListener('pointerdown',resetIdle,{passive:true});
  document.addEventListener('keydown',e=>{resetIdle();if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a'){state.admin=true;render();}if(e.key==='Escape'&&state.admin){state.admin=false;render();}});
  render();
})();
